input-field {
    monitor =
    size = 320, 60
    outline_thickness = 2
    dots_text_format = 々
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    check_color = $lock_accent
    outer_color = $lock_surface
    inner_color = $lock_surface
    font_color = $lock_foreground
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = $USER
    fail_text = <i>$PAMFAIL</i>
    hide_input = false
    position = 0, -250
    halign = center
    valign = center
}
