general {
    immediate_render = true
    ignore_empty_input = true
    hide_cursor = true
}

auth {
    pam {
        enabled = true
        module = hyprlock
    }
}

background {
    monitor =
    path = ~/.local/state/omarchy/current/background
    blur_passes = 3
    blur_size = 7
    noise = 0.02
    contrast = 1.0
    brightness = 0.8
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}

animations {
    enabled = true
    bezier = premiumSmooth, 0.2, 0, 0.25, 1
    animation = fadeIn, 1, 4, premiumSmooth
    animation = fadeOut, 1, 4, premiumSmooth
    animation = inputFieldDots, 1, 3, premiumSmooth
}
