# Adapted from https://github.com/wolfykq/dotfiles/tree/main/.config/hypr
# Mac-blur-quattro: current wallpaper, dynamic palette, and a 12-hour clock.
source = ~/.config/hypr/hyprlock/colors.conf
source = ~/.config/hypr/hyprlock/settings.conf
source = ~/.config/hypr/hyprlock/labels.conf
source = ~/.config/hypr/hyprlock/input_field.conf
